"""
This module stores team information from whoscored.com: 
teamID: Team name and ID Currently only for the Spanish La Liga
filteredFeatures: features selected by me...
This is the latest version: features added for contrast terms like long/short passes
"""

teamIDs = [(52, 'Real-Madrid'),
 (65, 'Barcelona'),
 (63, 'Atletico-Madrid'),
 (55, 'Valencia'),
 (67, 'Sevilla'),
 (839, 'Villarreal'),
 (69, 'Malaga'),
 (824, 'Eibar'),
 (70, 'Espanyol'),
 (64, 'Rayo-Vallecano'),
 (62, 'Celta-Vigo'),
 (53, 'Athletic-Club'),
 (68, 'Real-Sociedad'),
 (820, 'Cordoba'),
 (819, 'Getafe'),
 (59, 'Deportivo-La-Coruna'),
 (832, 'Levante'),
 (1799, 'Almeria'),
 (925, 'Granada'),
 (833, 'Elche')]

teamRelegate = ['Osasuna',
 'Valladolid',
 'Real-Betis',
 'Mallorca',
 'Deportivo-La-Coruna',
 'Zaragoza',
 'Villarreal',
 'Sporting-Gijon',
 'Racing-Santander',
 'Hercules',
 'Almeria']

filteredFeatures = ['accurate_corners_intobox',
 'accurate_freekick_cross',
 'accurate_cross',
 'accurate_long_balls',
 'accurate_pass',
 'accurate_through_ball',
 'aerial_won',
 'att_fastbreak',
 'att_hd_total',
 'att_obox_miss',
 'att_obox_target',
 'att_ibox_miss',
 'att_ibox_target',
 'backward_pass',
 'corner_taken',
 'crosses_18yard',
 'crosses_18yardplus',
 'dispossessed',
 'dribble_lost',
 'duel_won',
 'effective_blocked_cross',
 'effective_clearance',
 'formation_used',
 'freekick_cross',
 'fwd_pass',
 'goals',
 'interception',
 'interception_won',
 'poss_lost_all',
 'possession_percentage',
 'shot_fastbreak',
 'shot_off_target',
 'subs_made',
 'total_att_assist',
 'total_corners_intobox',
 'total_cross',
 'total_fastbreak',
 'total_long_balls',
 'total_pass',
 'total_scoring_att',
 'total_tackle',
 'total_through_ball',
 'won_corners',
 'won_tackle']
